### ISSUE TITLE
如何在vscode debug nodejs的时候使用nodemon？

### ISSUE THREAD

**Issue by cike8899** [i5ting/vsc#6]
"scripts": {
    "dev": "nodemon -w src --exec \"babel-node src --presets es2015,stage-0\""
  },

然后运行npm run dev,浏览器就可以访问项目了

launch.json 配置如下

 {
      "name": "附加",
      "type": "node",
      "request": "attach",
      "port": 8080,
      "address": "localhost",
      "restart": false,
      "sourceMaps": false,
      "outDir": null,
      "localRoot": "${workspaceRoot}",
      "remoteRoot": null
 },

然后点击vscode上的运行按钮，运行起来了，但是这个运行按钮的框在不停的跳动，浏览器访问也走不到断点，运行launch 按钮的时候是可以debug的。这是为啥呢？
官网上说的也不够明确，看了一遍文章nodemon_vscode，也没办法运行起来！

**Comment by i5ting** [comment]
这个貌似不现实，直接node吧，如果文件变动，nodemon重启node之后debugger怎么知道呢？

**Comment by cike8899** [comment]
如果用vscode调试nodejs，每次文件变化都要rebuild？有什么好的解决办法吗？

**Comment by i5ting** [comment]
除了tdd/bdd外，vscode的debug是无解的

**Comment by cike8899** [comment]
tdd/bdd 是啥意思？
